# File: .github/workflows/repo-sync.yml
name: 同步 Actions_JX 和 jd_scripts
on:
  schedule:
    - cron: '2 0,8,16 * * *'
  workflow_dispatch:
  watch:
    types: started
  repository_dispatch:
    types: Sync_Actions_JX_and_jd_scripts
jobs:
  repo-sync:
    env:
      PAT: ${{ secrets.PAT }} #此处PAT需要申请，教程详见：https://www.jianshu.com/p/bb82b3ad1d11
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v2
        with:
          repository_dispatch: false

      - name: sync Sync_Actions_JX
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/jiegto/Actions_JX.git"
          source_branch: "main"
          destination_branch: "main"
          github_token: ${{ secrets.PAT }}

      - name: sync Sync_jd_scripts
        uses: repo-sync/github-sync@v2
        if: env.PAT
        with:
          source_repo: "https://github.com/LXK9301/jd_scripts.git"
          source_branch: "master"
          destination_branch: "master"
          github_token: ${{ secrets.PAT }}
